<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Client;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClientSeeder extends Seeder
{
    public function run(): void
    {
        // ⚠️ Désactiver les clés étrangères pour éviter les conflits
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        // 🧹 Vider la table (remise à zéro)
        Client::truncate();

        // ✅ Réactiver les clés étrangères
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        // ✅ APPROCHE DIRECTE : IDs directs (simple et performant)
        $clients = [
            ['code' => 'CL000', 'fullName' => 'ELHILALY ABDENNABI', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 1, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL001', 'fullName' => 'LHAJ LHASSROUF', 'telephone' => '', 'idVille' => 1, 'idSecteur' => 10, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL002', 'fullName' => 'TAFOUKT YOUSSEF', 'telephone' => '', 'idVille' => 1, 'idSecteur' => 10, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL003', 'fullName' => 'CHIRAOUI ABDERRAHMANE', 'telephone' => '', 'idVille' => 2, 'idSecteur' => 16, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL004', 'fullName' => 'OUBARI MBAREK', 'telephone' => '', 'idVille' => 3, 'idSecteur' => 7, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL005', 'fullName' => 'OUCHEN MOHAMED', 'telephone' => '', 'idVille' => 1, 'idSecteur' => 10, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL006', 'fullName' => 'BENTAHER HAMID', 'telephone' => '', 'idVille' => 3, 'idSecteur' => 7, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL007', 'fullName' => 'AHMED NADAFA', 'telephone' => '', 'idVille' => 4, 'idSecteur' => 4, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL008', 'fullName' => 'KHALED BEN TAHER', 'telephone' => '', 'idVille' => 1, 'idSecteur' => 10, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL009', 'fullName' => 'OUMAST LAHCEN', 'telephone' => '', 'idVille' => 5, 'idSecteur' => 6, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL010', 'fullName' => 'AZOUZ MOHAMED', 'telephone' => '', 'idVille' => 1, 'idSecteur' => 10, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL011', 'fullName' => 'LHAJ HASSAN EL AADODI', 'telephone' => '', 'idVille' => 6, 'idSecteur' => 3, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL012', 'fullName' => 'AFRIAD MOHAMED', 'telephone' => '', 'idVille' => 1, 'idSecteur' => 10, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL013', 'fullName' => 'LHAJ LAAZIB', 'telephone' => '', 'idVille' => 2, 'idSecteur' => 14, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL014', 'fullName' => 'RARA RABII', 'telephone' => '', 'idVille' => 7, 'idSecteur' => 19, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL015', 'fullName' => 'ADERQAOU LHAJ HASSAN', 'telephone' => '', 'idVille' => 6, 'idSecteur' => 3, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL016', 'fullName' => 'ABRABRI ABDELLAH', 'telephone' => '', 'idVille' => 1, 'idSecteur' => 10, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL017', 'fullName' => 'TAFRAOUT', 'telephone' => '', 'idVille' => 8, 'idSecteur' => 5, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL018', 'fullName' => 'ANAROUZ', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 8, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL019', 'fullName' => 'ALI LAAZIB', 'telephone' => '', 'idVille' => 2, 'idSecteur' => 14, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL020', 'fullName' => 'ABDELLAH ADRAR', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 2, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL021', 'fullName' => 'BAHA MOHAMED', 'telephone' => '', 'idVille' => 10, 'idSecteur' => 17, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL022', 'fullName' => 'ELMOUDEN SAID', 'telephone' => '', 'idVille' => 6, 'idSecteur' => 3, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL023', 'fullName' => 'AAROUF TADDART', 'telephone' => '', 'idVille' => 11, 'idSecteur' => 23, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL024', 'fullName' => 'CHMOURRE MOHAMED', 'telephone' => '', 'idVille' => 1, 'idSecteur' => 10, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL025', 'fullName' => 'RAHHAL BIMGHAREN', 'telephone' => '', 'idVille' => 1, 'idSecteur' => 24, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL026', 'fullName' => 'SALEH AIT BOUTAIB', 'telephone' => '', 'idVille' => 10, 'idSecteur' => 17, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL027', 'fullName' => 'KASMI LAQLIAA', 'telephone' => '', 'idVille' => 2, 'idSecteur' => 16, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL028', 'fullName' => 'ZOUHARI SAID', 'telephone' => '', 'idVille' => 2, 'idSecteur' => 16, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL029', 'fullName' => 'KALTOUMA EL MELLALI', 'telephone' => '', 'idVille' => 1, 'idSecteur' => 10, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL030', 'fullName' => 'GRICH ABDESSAMAD', 'telephone' => '', 'idVille' => 12, 'idSecteur' => 21, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL031', 'fullName' => 'SAID OULAD DAHOU', 'telephone' => '', 'idVille' => 7, 'idSecteur' => 19, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL032', 'fullName' => 'WARGHEN ABDELAZIZ', 'telephone' => '', 'idVille' => 3, 'idSecteur' => 7, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL033', 'fullName' => 'TALLA LAQUAIA', 'telephone' => '', 'idVille' => 2, 'idSecteur' => 16, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL034', 'fullName' => 'DAAF AYOUB', 'telephone' => '', 'idVille' => 1, 'idSecteur' => 10, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL035', 'fullName' => 'BATTIN ABDELIAH', 'telephone' => '', 'idVille' => 4, 'idSecteur' => 4, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL036', 'fullName' => 'AZOUGAY MOHAMED', 'telephone' => '', 'idVille' => 2, 'idSecteur' => 16, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL037', 'fullName' => 'AIT BRIK AHMED', 'telephone' => '', 'idVille' => 4, 'idSecteur' => 4, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL038', 'fullName' => 'REDA LQODS', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 9, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL039', 'fullName' => 'DAAF MOHAMED', 'telephone' => '', 'idVille' => 1, 'idSecteur' => 10, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL040', 'fullName' => 'LHAJ MOUSSA', 'telephone' => '', 'idVille' => 4, 'idSecteur' => 13, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL041', 'fullName' => 'AZZOUZ KHAUD', 'telephone' => '', 'idVille' => 1, 'idSecteur' => 10, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL042', 'fullName' => 'AKOUBASS SALFH', 'telephone' => '', 'idVille' => 4, 'idSecteur' => 4, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL043', 'fullName' => 'BOURCHOUM BRAHIM', 'telephone' => '', 'idVille' => 1, 'idSecteur' => 10, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL044', 'fullName' => 'AIT TAMAZIRT MOHAMED', 'telephone' => '', 'idVille' => 7, 'idSecteur' => 19, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL045', 'fullName' => 'DAAF SAID', 'telephone' => '', 'idVille' => 1, 'idSecteur' => 10, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL046', 'fullName' => 'HAMOUDA TARRAST', 'telephone' => '', 'idVille' => 1, 'idSecteur' => 24, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL047', 'fullName' => 'ABRABRI LAQUAIA', 'telephone' => '', 'idVille' => 2, 'idSecteur' => 16, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL048', 'fullName' => 'ELMANSSOURI MBAREK', 'telephone' => '06 61 47 43 56', 'idVille' => 1, 'idSecteur' => 10, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL049', 'fullName' => 'ALWANNAS', 'telephone' => '', 'idVille' => 13, 'idSecteur' => 11, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL050', 'fullName' => 'DAHOUZ ABDELIAH', 'telephone' => '', 'idVille' => 14, 'idSecteur' => 15, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL051', 'fullName' => 'HADDI MOHAMED', 'telephone' => '', 'idVille' => 15, 'idSecteur' => 26, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL052', 'fullName' => 'BAZGRA ALI', 'telephone' => '', 'idVille' => 1, 'idSecteur' => 24, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL053', 'fullName' => 'MUSTAPHA', 'telephone' => '', 'idVille' => 15, 'idSecteur' => 26, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL054', 'fullName' => 'TALLA ISMAIL', 'telephone' => '', 'idVille' => 4, 'idSecteur' => 4, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL055', 'fullName' => 'SABER AHMED', 'telephone' => '', 'idVille' => 4, 'idSecteur' => 22, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL056', 'fullName' => 'MOHAMED LAAZIB', 'telephone' => '', 'idVille' => 2, 'idSecteur' => 14, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL057', 'fullName' => 'HAMAMI LAHICEN', 'telephone' => '', 'idVille' => 1, 'idSecteur' => 12, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL058', 'fullName' => 'AATAR LHAJ HASSAN', 'telephone' => '', 'idVille' => 6, 'idSecteur' => 3, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL059', 'fullName' => 'EL MELLALI ABDELMOUNAAIM', 'telephone' => '', 'idVille' => 1, 'idSecteur' => 10, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL060', 'fullName' => 'TALBI BIOGRA', 'telephone' => '', 'idVille' => 3, 'idSecteur' => 7, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL061', 'fullName' => 'CHIDMI SAID', 'telephone' => '', 'idVille' => 2, 'idSecteur' => 14, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL062', 'fullName' => 'AOERQAOU OMAR', 'telephone' => '', 'idVille' => 6, 'idSecteur' => 3, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL063', 'fullName' => 'BELFQIR TEMSSIA', 'telephone' => '', 'idVille' => 4, 'idSecteur' => 25, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL064', 'fullName' => 'BEN YAHYA MOHAMED', 'telephone' => '', 'idVille' => 3, 'idSecteur' => 7, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL065', 'fullName' => 'FARAH MOHAMED', 'telephone' => '', 'idVille' => 4, 'idSecteur' => 22, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL066', 'fullName' => 'MLIHA ABDELHAKIM', 'telephone' => '', 'idVille' => 4, 'idSecteur' => 4, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL067', 'fullName' => 'AMHDAR LHAJ HASSAN', 'telephone' => '', 'idVille' => 1, 'idSecteur' => 10, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL068', 'fullName' => 'WAHMAN LAHOUCINE', 'telephone' => '', 'idVille' => 6, 'idSecteur' => 3, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL069', 'fullName' => 'BENGARDE MOHAMED', 'telephone' => '', 'idVille' => 6, 'idSecteur' => 3, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL070', 'fullName' => 'LHAJ ALI MASSA', 'telephone' => '', 'idVille' => 16, 'idSecteur' => 18, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL071', 'fullName' => 'LHAJ ALI AIT MILK', 'telephone' => '', 'idVille' => 17, 'idSecteur' => 20, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL072', 'fullName' => 'QASSIMI BRAHIM', 'telephone' => '', 'idVille' => 18, 'idSecteur' => 28, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL073', 'fullName' => 'AMACHOUCH ABDELLAH', 'telephone' => '', 'idVille' => 2, 'idSecteur' => 16, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL074', 'fullName' => 'MENOUAL AHMED', 'telephone' => '', 'idVille' => 1, 'idSecteur' => 24, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL075', 'fullName' => 'AYDOUN LAHCEN', 'telephone' => '', 'idVille' => 13, 'idSecteur' => 11, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL076', 'fullName' => 'ALIOUA', 'telephone' => '', 'idVille' => 18, 'idSecteur' => 28, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL077', 'fullName' => 'RACHID BAYTLAHM', 'telephone' => '', 'idVille' => 1, 'idSecteur' => 10, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL078', 'fullName' => 'ABIDAR OMAR', 'telephone' => '', 'idVille' => 17, 'idSecteur' => 20, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL079', 'fullName' => 'BIGAROUR LHAJ MBARK', 'telephone' => '', 'idVille' => 5, 'idSecteur' => 6, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL080', 'fullName' => 'AARROUB', 'telephone' => '', 'idVille' => 8, 'idSecteur' => 5, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL081', 'fullName' => 'OMAR RAHL', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 1, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL082', 'fullName' => 'LABZA FTTAH', 'telephone' => '', 'idVille' => 13, 'idSecteur' => 11, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL083', 'fullName' => 'ABDELHAFID', 'telephone' => '', 'idVille' => 2, 'idSecteur' => 16, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL084', 'fullName' => 'AZOUZ SAID', 'telephone' => '', 'idVille' => 19, 'idSecteur' => 29, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL085', 'fullName' => 'ABDELLAH DRARGA', 'telephone' => '', 'idVille' => 19, 'idSecteur' => 29, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL086', 'fullName' => 'BAZGRA LHAJ HAMID', 'telephone' => '', 'idVille' => 1, 'idSecteur' => 10, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL087', 'fullName' => 'MOKHLISSE MOHAMMED', 'telephone' => '', 'idVille' => 3, 'idSecteur' => 7, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL088', 'fullName' => 'DAHOUZ ABDELAZIZ', 'telephone' => '', 'idVille' => 14, 'idSecteur' => 15, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL089', 'fullName' => 'MOUTAWAKIL BRAHIM', 'telephone' => '', 'idVille' => 1, 'idSecteur' => 10, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL090', 'fullName' => 'LKABOUSS', 'telephone' => '', 'idVille' => 18, 'idSecteur' => 28, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL091', 'fullName' => 'BOUSKID ABDELMAJID', 'telephone' => '', 'idVille' => 1, 'idSecteur' => 10, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL092', 'fullName' => 'LHAJ HMMOUCH', 'telephone' => '', 'idVille' => 5, 'idSecteur' => 6, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL093', 'fullName' => 'DAAIF SALEH', 'telephone' => '', 'idVille' => 5, 'idSecteur' => 6, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL094', 'fullName' => 'SAFI ABDELLATIF', 'telephone' => '', 'idVille' => 20, 'idSecteur' => 30, 'idCommercial' => 1, 'remise_special' => 2, 'pourcentage' => 0],
            ['code' => 'CL095', 'fullName' => 'KHALIFA ESSAKHI', 'telephone' => '', 'idVille' => 22, 'idSecteur' => 32, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL096', 'fullName' => 'MEHDI RECLAM', 'telephone' => '', 'idVille' => 2, 'idSecteur' => 16, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL097', 'fullName' => 'MOHAMMAD LAQLIAA', 'telephone' => '', 'idVille' => 2, 'idSecteur' => 16, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL098', 'fullName' => 'NOUREDDINE BOUNDIF', 'telephone' => '', 'idVille' => 21, 'idSecteur' => 31, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL099', 'fullName' => 'ABDELLAH 5DH', 'telephone' => '', 'idVille' => 23, 'idSecteur' => 33, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL100', 'fullName' => 'YOUSSEF', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 27, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL101', 'fullName' => 'OUISSNI ABDELJAUL', 'telephone' => '', 'idVille' => 1, 'idSecteur' => 24, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL102', 'fullName' => 'ABDELFATTAH ELGHAYTI', 'telephone' => '', 'idVille' => 1, 'idSecteur' => 10, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL103', 'fullName' => 'MOHAMMED TAMAATI', 'telephone' => '', 'idVille' => 24, 'idSecteur' => 34, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL104', 'fullName' => 'JAMAA LAKHCHICHA', 'telephone' => '', 'idVille' => 1, 'idSecteur' => 10, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL105', 'fullName' => 'AYOUB SM TAOURIRTE', 'telephone' => '', 'idVille' => 8, 'idSecteur' => 5, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL106', 'fullName' => 'LHAJ HASSAN AOURIR', 'telephone' => '', 'idVille' => 25, 'idSecteur' => 35, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL107', 'fullName' => 'AJATAY HAMID', 'telephone' => '', 'idVille' => 25, 'idSecteur' => 35, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL108', 'fullName' => 'MOHAMED AMBULANT', 'telephone' => '', 'idVille' => 4, 'idSecteur' => 35, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL109', 'fullName' => 'RACHID HIHI', 'telephone' => '', 'idVille' => 8, 'idSecteur' => 5, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL110', 'fullName' => 'AROUB ALI', 'telephone' => '', 'idVille' => 8, 'idSecteur' => 5, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL111', 'fullName' => 'DRISTADDRAT', 'telephone' => '', 'idVille' => 11, 'idSecteur' => 23, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL112', 'fullName' => 'MJID AOURIR', 'telephone' => '', 'idVille' => 25, 'idSecteur' => 35, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL113', 'fullName' => 'HASSAN HMMOUCH', 'telephone' => '', 'idVille' => 25, 'idSecteur' => 35, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL114', 'fullName' => 'HASSAN AGHIJE', 'telephone' => '', 'idVille' => 25, 'idSecteur' => 35, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL115', 'fullName' => 'MATJAR ALAKHAWAYN', 'telephone' => '', 'idVille' => 25, 'idSecteur' => 35, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL116', 'fullName' => 'HICHAM BEN ALI', 'telephone' => '', 'idVille' => 25, 'idSecteur' => 35, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL117', 'fullName' => 'ABDELLAH ONASSER', 'telephone' => '', 'idVille' => 25, 'idSecteur' => 35, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL118', 'fullName' => 'COOPERATIVE AIT SI SALEM', 'telephone' => '', 'idVille' => 10, 'idSecteur' => 17, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL119', 'fullName' => 'MOHAMMAD JAZZA', 'telephone' => '', 'idVille' => 19, 'idSecteur' => 29, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL120', 'fullName' => 'HARDA RACHID', 'telephone' => '', 'idVille' => 4, 'idSecteur' => 4, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL121', 'fullName' => 'BOFOUS MOHAMMAD', 'telephone' => '', 'idVille' => 8, 'idSecteur' => 5, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL122', 'fullName' => 'DRISTABORHARI', 'telephone' => '', 'idVille' => 8, 'idSecteur' => 5, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL123', 'fullName' => 'SALEH AZROU', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 36, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL124', 'fullName' => 'OUSSAMA REKLAM', 'telephone' => '', 'idVille' => 8, 'idSecteur' => 5, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL125', 'fullName' => 'BOBAKER DARNA', 'telephone' => '', 'idVille' => 26, 'idSecteur' => 38, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL126', 'fullName' => 'BRAHIM ELYAZIDI', 'telephone' => '', 'idVille' => 12, 'idSecteur' => 21, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL127', 'fullName' => 'HEBBACH MOHAMED', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 39, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL128', 'fullName' => 'ELHOUSSINE ELYAZID', 'telephone' => '', 'idVille' => 4, 'idSecteur' => 42, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL129', 'fullName' => 'LAARBI BINANFAR', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 39, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL130', 'fullName' => 'LAHCCN BOUIAMAA', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 9, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL131', 'fullName' => 'ABDELHAMID ANQUAR', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 40, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL132', 'fullName' => 'AZIZ BOUBAKER', 'telephone' => '', 'idVille' => 24, 'idSecteur' => 34, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL133', 'fullName' => 'HASSAN TAMAATT', 'telephone' => '', 'idVille' => 24, 'idSecteur' => 34, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL134', 'fullName' => 'LAHICEN ABAAMRAN', 'telephone' => '', 'idVille' => 1, 'idSecteur' => 24, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL135', 'fullName' => 'CHRIF MOHAMMED', 'telephone' => '', 'idVille' => 8, 'idSecteur' => 5, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL136', 'fullName' => 'AHBIB BRAHIM', 'telephone' => '', 'idVille' => 21, 'idSecteur' => 31, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL137', 'fullName' => 'MATJAR KATA', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 27, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL138', 'fullName' => 'BRAHIM LAATTAR', 'telephone' => '', 'idVille' => 4, 'idSecteur' => 41, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL139', 'fullName' => 'MATJAR DARNA', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 36, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL140', 'fullName' => 'OUBILLA ABDERRAHMAN', 'telephone' => '', 'idVille' => 21, 'idSecteur' => 31, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL141', 'fullName' => 'BEN CHOUAF', 'telephone' => '', 'idVille' => 19, 'idSecteur' => 29, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL142', 'fullName' => 'ALLIGHOL', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 27, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL143', 'fullName' => 'NOUREDDINE YOUSSOUFIA', 'telephone' => '', 'idVille' => 15, 'idSecteur' => 26, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL144', 'fullName' => 'ABDELLAH AMZIGH', 'telephone' => '', 'idVille' => 15, 'idSecteur' => 26, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL145', 'fullName' => 'BENYOUSSEF MUSTAPHA', 'telephone' => '', 'idVille' => 15, 'idSecteur' => 26, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL146', 'fullName' => 'SUPERETTE ALHOUSSINE', 'telephone' => '', 'idVille' => 12, 'idSecteur' => 21, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL147', 'fullName' => 'BEN YAHYA ADIL', 'telephone' => '', 'idVille' => 6, 'idSecteur' => 3, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL148', 'fullName' => 'BELYAZIDE MUSTAPHA', 'telephone' => '', 'idVille' => 6, 'idSecteur' => 3, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL149', 'fullName' => 'SUPERETTE LE GRARA', 'telephone' => '', 'idVille' => 12, 'idSecteur' => 21, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL150', 'fullName' => 'MOHAMAD DRAYD', 'telephone' => '', 'idVille' => 12, 'idSecteur' => 21, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL151', 'fullName' => 'ABDELKHALEG ELOAHOUI', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 36, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL152', 'fullName' => 'DRIS BOUNDIF', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 40, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL153', 'fullName' => 'HANNIN DAOUDIE', 'telephone' => '', 'idVille' => 27, 'idSecteur' => 41, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 2],
            ['code' => 'CL154', 'fullName' => 'AMZEL LAHOUSSINE', 'telephone' => '', 'idVille' => 4, 'idSecteur' => 42, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL155', 'fullName' => 'CHAIBA SOJUGUI', 'telephone' => '', 'idVille' => 2, 'idSecteur' => 43, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL156', 'fullName' => 'ABDESSAMAD WAGHI', 'telephone' => '', 'idVille' => 6, 'idSecteur' => 3, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL157', 'fullName' => 'SALEM BALHOUSS', 'telephone' => '', 'idVille' => 18, 'idSecteur' => 28, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL158', 'fullName' => 'MOHAMMAD CHOHADA', 'telephone' => '', 'idVille' => 4, 'idSecteur' => 44, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL159', 'fullName' => 'ABDEDAYEM TIKIOUN', 'telephone' => '', 'idVille' => 26, 'idSecteur' => 38, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL160', 'fullName' => 'MOHAMMAD LMARCHI', 'telephone' => '', 'idVille' => 2, 'idSecteur' => 16, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL161', 'fullName' => 'LHAJ ABBDE', 'telephone' => '', 'idVille' => 19, 'idSecteur' => 29, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL162', 'fullName' => 'AGRZAM LAHICEN', 'telephone' => '', 'idVille' => 25, 'idSecteur' => 35, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL163', 'fullName' => 'MATJAR ASSAFA', 'telephone' => '06 71 43 26 20', 'idVille' => 9, 'idSecteur' => 27, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL164', 'fullName' => 'BRAHIM LAQLIAA', 'telephone' => '', 'idVille' => 2, 'idSecteur' => 16, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL165', 'fullName' => 'HASSAN ELFARAH', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 45, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL166', 'fullName' => 'MOUHSIN ELKASBA', 'telephone' => '', 'idVille' => 4, 'idSecteur' => 13, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL167', 'fullName' => 'JAMAA ELMASSIRA', 'telephone' => '', 'idVille' => 4, 'idSecteur' => 41, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL168', 'fullName' => 'SUPERETTE TIOGHZA', 'telephone' => '', 'idVille' => 25, 'idSecteur' => 35, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL169', 'fullName' => 'OMAR HAJJI', 'telephone' => '', 'idVille' => 13, 'idSecteur' => 11, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL170', 'fullName' => 'ISMAIL ELMASSIRA', 'telephone' => '', 'idVille' => 4, 'idSecteur' => 41, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL171', 'fullName' => 'ARKHA MOHAMED', 'telephone' => '', 'idVille' => 26, 'idSecteur' => 38, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL172', 'fullName' => 'HASSAN ACHTOUK', 'telephone' => '', 'idVille' => 26, 'idSecteur' => 38, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL173', 'fullName' => 'SAID BOUFOUSS', 'telephone' => '', 'idVille' => 8, 'idSecteur' => 5, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL174', 'fullName' => 'DRISS ANZA', 'telephone' => '', 'idVille' => 11, 'idSecteur' => 46, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL175', 'fullName' => 'SUPERETTE HICHAM', 'telephone' => '', 'idVille' => 11, 'idSecteur' => 23, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL176', 'fullName' => 'SAID ANZA', 'telephone' => '', 'idVille' => 11, 'idSecteur' => 46, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL177', 'fullName' => 'AHMED ALMOUSTAQBAL', 'telephone' => '', 'idVille' => 4, 'idSecteur' => 47, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL178', 'fullName' => 'ABDELLAH RMAL', 'telephone' => '', 'idVille' => 1, 'idSecteur' => 48, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL179', 'fullName' => 'AHMED TEMSSIA', 'telephone' => '', 'idVille' => 4, 'idSecteur' => 25, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL180', 'fullName' => 'ABDELKABIR DOUKALI', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 45, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL181', 'fullName' => 'YOUSSEF SEHRAOUI', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 36, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL182', 'fullName' => 'MATJAR ALAKHAWAYN JAMAL', 'telephone' => '', 'idVille' => 3, 'idSecteur' => 7, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL183', 'fullName' => 'SAID LAAZIB', 'telephone' => '', 'idVille' => 2, 'idSecteur' => 14, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL184', 'fullName' => 'MBAREK BOUNDIF', 'telephone' => '', 'idVille' => 4, 'idSecteur' => 47, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL185', 'fullName' => 'ABDELAH LMARCHI', 'telephone' => '', 'idVille' => 8, 'idSecteur' => 5, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL186', 'fullName' => 'ECOPRIX AMOGAY', 'telephone' => '', 'idVille' => 21, 'idSecteur' => 49, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL187', 'fullName' => 'ABDELLAH AOURIR', 'telephone' => '', 'idVille' => 25, 'idSecteur' => 35, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL188', 'fullName' => 'RACHID DRARGA', 'telephone' => '', 'idVille' => 19, 'idSecteur' => 29, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL189', 'fullName' => 'RAISS AIT BAHA', 'telephone' => '', 'idVille' => 28, 'idSecteur' => 50, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL190', 'fullName' => 'YOUSSEF TEMSSIA', 'telephone' => '', 'idVille' => 4, 'idSecteur' => 25, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL191', 'fullName' => 'SAID TAMAAIT', 'telephone' => '06 67 38 35 29', 'idVille' => 24, 'idSecteur' => 34, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL192', 'fullName' => 'SAID SWIQA', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 45, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL193', 'fullName' => 'ADIL CHYOUKH', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 51, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL194', 'fullName' => 'LHAJ HASSAN ELFARAH', 'telephone' => '06 35 45 22 26', 'idVille' => 9, 'idSecteur' => 45, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL195', 'fullName' => 'OMAR SPEED', 'telephone' => '', 'idVille' => 1, 'idSecteur' => 10, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL196', 'fullName' => 'AHMED HAJJI', 'telephone' => '', 'idVille' => 4, 'idSecteur' => 25, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL197', 'fullName' => 'RACHID LATAR', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 45, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL198', 'fullName' => 'MATJAR JAWAD', 'telephone' => '', 'idVille' => 4, 'idSecteur' => 44, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL199', 'fullName' => 'RACHID BOUCHTART', 'telephone' => '', 'idVille' => 15, 'idSecteur' => 26, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL200', 'fullName' => 'LAHGEN ABOURRAR', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 27, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL201', 'fullName' => 'ABDELLAH BOUFOUSS', 'telephone' => '', 'idVille' => 8, 'idSecteur' => 5, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL202', 'fullName' => 'HASSAN BENSERGAOU', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 40, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL203', 'fullName' => 'MOHAMED ABOURRAR', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 40, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL204', 'fullName' => 'DAAIF AIT BOUTAIB', 'telephone' => '', 'idVille' => 10, 'idSecteur' => 17, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL205', 'fullName' => 'MOURISIN TANTAN', 'telephone' => '', 'idVille' => 18, 'idSecteur' => 28, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL206', 'fullName' => 'OUZDOU OMAR', 'telephone' => '', 'idVille' => 18, 'idSecteur' => 28, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL207', 'fullName' => 'LAHGEN BONDIF', 'telephone' => '', 'idVille' => 4, 'idSecteur' => 52, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL208', 'fullName' => 'HASSAN DOUAR IZDDAR', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 40, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL209', 'fullName' => 'HAFID LORIKA', 'telephone' => '', 'idVille' => 2, 'idSecteur' => 16, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL210', 'fullName' => 'AGENCE IMMOBILIÈRE INDY', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 27, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL211', 'fullName' => 'BRAHIM TILLA', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 53, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL212', 'fullName' => 'MOHAMMED TADAMOUN', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 36, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL213', 'fullName' => 'CHIRAOUI ABDERRAHMANE 2', 'telephone' => '', 'idVille' => 2, 'idSecteur' => 16, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL214', 'fullName' => 'MOHAMED AIT MILK', 'telephone' => '', 'idVille' => 17, 'idSecteur' => 20, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL215', 'fullName' => 'ABDELGHN ABOU JOUAYRIYA', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 45, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL216', 'fullName' => 'HASSAN ELGMRANI', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 45, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL217', 'fullName' => 'ABDELAH CHAOROUN', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 40, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL218', 'fullName' => 'DRIS ISSAFEN', 'telephone' => '', 'idVille' => 8, 'idSecteur' => 5, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL219', 'fullName' => 'MATJAR AL-SSAHIL', 'telephone' => '', 'idVille' => 25, 'idSecteur' => 58, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL220', 'fullName' => 'ANJAR AHMED', 'telephone' => '', 'idVille' => 15, 'idSecteur' => 26, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL221', 'fullName' => 'LHAJ LAHGEN BOUNDIF', 'telephone' => '', 'idVille' => 21, 'idSecteur' => 31, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL222', 'fullName' => 'BIGAROUR RACHID', 'telephone' => '', 'idVille' => 12, 'idSecteur' => 21, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL223', 'fullName' => 'ANAROUZ 2', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 8, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL224', 'fullName' => 'SMAIL AMJAR', 'telephone' => '', 'idVille' => 15, 'idSecteur' => 26, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL225', 'fullName' => 'HOUSSIH QASSEM', 'telephone' => '06 71 20 52 85', 'idVille' => 4, 'idSecteur' => 41, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL226', 'fullName' => 'REDOUANE ABOU SALAH', 'telephone' => '06 00 31 95 07', 'idVille' => 4, 'idSecteur' => 54, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL227', 'fullName' => 'LAHSEN HIHI', 'telephone' => '06 77 53 92 61', 'idVille' => 9, 'idSecteur' => 56, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL228', 'fullName' => 'MOHAMED MARZOUK', 'telephone' => '', 'idVille' => 15, 'idSecteur' => 26, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL229', 'fullName' => 'BIGAROUR LAHGEN', 'telephone' => '', 'idVille' => 12, 'idSecteur' => 21, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL230', 'fullName' => 'ABDELLAH BELFAGIR', 'telephone' => '06 71 66 42 45', 'idVille' => 3, 'idSecteur' => 7, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL231', 'fullName' => 'MUSTAPHA AABIR', 'telephone' => '', 'idVille' => 3, 'idSecteur' => 7, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL232', 'fullName' => 'LAHCCN 11 JANVIER', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 27, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL233', 'fullName' => 'BRAHIM BENSERGAOU', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 40, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL234', 'fullName' => 'ELMAHFOUD OUCHNI', 'telephone' => '', 'idVille' => 4, 'idSecteur' => 25, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL235', 'fullName' => 'ABDELLAH ELAATAR', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 40, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL236', 'fullName' => 'YOUNESS ALMOURAKAB', 'telephone' => '', 'idVille' => 4, 'idSecteur' => 35, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL237', 'fullName' => 'HASSAN LKHDAR', 'telephone' => '', 'idVille' => 13, 'idSecteur' => 11, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL238', 'fullName' => 'ABAAIS BOUIEMAA', 'telephone' => '06 73 65 92 83', 'idVille' => 9, 'idSecteur' => 27, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL239', 'fullName' => 'BOUDERKA BRAHIM', 'telephone' => '', 'idVille' => 29, 'idSecteur' => 57, 'idCommercial' => 3, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL240', 'fullName' => 'ESSAGHIRI ABDELAIL', 'telephone' => '', 'idVille' => 27, 'idSecteur' => 41, 'idCommercial' => 4, 'remise_special' => 0, 'pourcentage' => 2],
            ['code' => 'CL241', 'fullName' => 'MOHAMED IKHRBAN', 'telephone' => '', 'idVille' => 4, 'idSecteur' => 25, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL242', 'fullName' => 'ADIL CHYOUKH EXZ', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 55, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL243', 'fullName' => 'ABDELLAH TAGHIJIT', 'telephone' => '', 'idVille' => 4, 'idSecteur' => 59, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL244', 'fullName' => 'ABDELLAH AOURIR2', 'telephone' => '', 'idVille' => 25, 'idSecteur' => 35, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL245', 'fullName' => 'ELAASRI LAHCCN', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 45, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL246', 'fullName' => 'MOHAMED ALMOUSTAQBAL', 'telephone' => '', 'idVille' => 4, 'idSecteur' => 47, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL247', 'fullName' => 'MOHAMED ISLANE', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 27, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL248', 'fullName' => 'NADIF MBAREK', 'telephone' => '', 'idVille' => 2, 'idSecteur' => 14, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL249', 'fullName' => 'LAHCCN MATJAR AYOUR', 'telephone' => '', 'idVille' => 5, 'idSecteur' => 6, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL250', 'fullName' => 'ABDELAH 9ARROUN', 'telephone' => '', 'idVille' => 11, 'idSecteur' => 23, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL251', 'fullName' => 'AABED SIDI BIBI', 'telephone' => '', 'idVille' => 12, 'idSecteur' => 21, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL252', 'fullName' => 'YOUSSEF ALAATAR', 'telephone' => '', 'idVille' => 12, 'idSecteur' => 21, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL253', 'fullName' => 'MOHAMMED ALIHADIA', 'telephone' => '06 18 02 54 06', 'idVille' => 1, 'idSecteur' => 10, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL254', 'fullName' => 'MUSTAPHA YOUSSOUFIA (Annuler)', 'telephone' => '', 'idVille' => 15, 'idSecteur' => 26, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL255', 'fullName' => 'MUSTAPHA DOUAR ALBANAN', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 40, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL256', 'fullName' => 'AHMED MINOUAL', 'telephone' => '', 'idVille' => 1, 'idSecteur' => 24, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL257', 'fullName' => 'SOCIETE SALAD HOUSE', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 27, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL258', 'fullName' => 'LAHCCN CHOUHADA', 'telephone' => '', 'idVille' => 4, 'idSecteur' => 44, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL259', 'fullName' => 'MOHAMMED ZGMOUNI', 'telephone' => '', 'idVille' => 26, 'idSecteur' => 38, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL260', 'fullName' => 'MATJAR ITTIFAQ', 'telephone' => '', 'idVille' => 15, 'idSecteur' => 26, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL261', 'fullName' => 'YOUNESS AL AKHAWAIN', 'telephone' => '', 'idVille' => 15, 'idSecteur' => 26, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL262', 'fullName' => 'MATJAR AL IZDIHAR', 'telephone' => '', 'idVille' => 15, 'idSecteur' => 26, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL263', 'fullName' => 'MOHAMMED SAADA', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 27, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL264', 'fullName' => 'LHOUSIN TARRAST', 'telephone' => '', 'idVille' => 1, 'idSecteur' => 24, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL265', 'fullName' => 'HAYAT AMZEL', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 40, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL266', 'fullName' => 'MOHAMED AIRAR', 'telephone' => '', 'idVille' => 15, 'idSecteur' => 60, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL267', 'fullName' => 'LHRI MARKET', 'telephone' => '06 96 85 08 60', 'idVille' => 9, 'idSecteur' => 8, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL268', 'fullName' => 'MUSTAPHA SAHRAOUI KHORBAN', 'telephone' => '', 'idVille' => 4, 'idSecteur' => 25, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL269', 'fullName' => 'OMAR TIGHERT', 'telephone' => '', 'idVille' => 15, 'idSecteur' => 61, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL270', 'fullName' => 'BELAAID TIGHERT', 'telephone' => '', 'idVille' => 15, 'idSecteur' => 61, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL271', 'fullName' => 'KHAILD ZITOUNI', 'telephone' => '', 'idVille' => 26, 'idSecteur' => 62, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL272', 'fullName' => 'ABDELLAH TAIBI', 'telephone' => '', 'idVille' => 2, 'idSecteur' => 63, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL273', 'fullName' => 'BRAHIM LOSBA', 'telephone' => '', 'idVille' => 4, 'idSecteur' => 52, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL274', 'fullName' => 'SALEH IKHRBAN', 'telephone' => '', 'idVille' => 4, 'idSecteur' => 25, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL275', 'fullName' => 'YOUNESS TAOURIRT', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 40, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL276', 'fullName' => 'YOUSSEF AGRO ELKENTAOUI', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 8, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL277', 'fullName' => 'MOHAMED DRARKA', 'telephone' => '', 'idVille' => 19, 'idSecteur' => 29, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL278', 'fullName' => 'AZIZ TIKWINE', 'telephone' => '', 'idVille' => 26, 'idSecteur' => 38, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL279', 'fullName' => 'ABDELLAH ALHOUDA', 'telephone' => '', 'idVille' => 9, 'idSecteur' => 8, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL280', 'fullName' => 'LAHCEN TAKHFIDAT LAHRI', 'telephone' => '', 'idVille' => 15, 'idSecteur' => 26, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL281', 'fullName' => 'MATJAR ABDELLAH LFSAL', 'telephone' => '', 'idVille' => 3, 'idSecteur' => 7, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL282', 'fullName' => 'MOHAMED BOUNDIF', 'telephone' => '', 'idVille' => 15, 'idSecteur' => 26, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL283', 'fullName' => 'RACHID LMZAR', 'telephone' => '', 'idVille' => 4, 'idSecteur' => 52, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL284', 'fullName' => 'SALEH TARRAST', 'telephone' => '', 'idVille' => 1, 'idSecteur' => 24, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL285', 'fullName' => 'BRAHIM TOYOTA', 'telephone' => '06 10 18 76 18', 'idVille' => 1, 'idSecteur' => 10, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL286', 'fullName' => 'RACHID BOURAKH', 'telephone' => '', 'idVille' => 8, 'idSecteur' => 5, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL287', 'fullName' => 'SUPERETTE HOUCINE', 'telephone' => '07 00 08 91 72', 'idVille' => 5, 'idSecteur' => 6, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL288', 'fullName' => 'LHAJ OMAR', 'telephone' => '06 67 39 87 06', 'idVille' => 10, 'idSecteur' => 17, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL289', 'fullName' => 'IMOUNAM MOHAMED', 'telephone' => '', 'idVille' => 15, 'idSecteur' => 26, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
            ['code' => 'CL290', 'fullName' => 'MOHAMED OUHMAD', 'telephone' => '05 28 23 16 83', 'idVille' => 9, 'idSecteur' => 64, 'idCommercial' => 2, 'remise_special' => 0, 'pourcentage' => 1],
            ['code' => 'CL291', 'fullName' => 'AYDOUN MOUSTAPHA', 'telephone' => '', 'idVille' => 13, 'idSecteur' => 11, 'idCommercial' => 1, 'remise_special' => 0, 'pourcentage' => 0],
        ];

        // Simple insertion directe - Pas de logique complexe !
        foreach ($clients as $client) {
            Client::create($client);
        }
    }
}
